/*
 * Generated by Abacus.
 */
package com.landawn.abacus.da.entity;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Generated by Abacus.
 * @version ${version}
 */
public interface ExtendDirtyBasicPNL {
    String _DN = "extendDirtyBasic".intern();

    public interface AccountPNL {
        /**
         * Name of "Account" entity.
         */
        String __ = "Account".intern();

        /**
         * Name of "id" property.
         * type: long.
         * column: "id".
         */
        String ID = (__ + ".id").intern();

        /**
         * Name of "gui" property.
         * type: String.
         * column: "gui".
         */
        String GUI = (__ + ".gui").intern();

        /**
         * Name of "emailAddress" property.
         * type: String.
         * column: "email_address".
         */
        String EMAIL_ADDRESS = (__ + ".emailAddress").intern();

        /**
         * Name of "firstName" property.
         * type: String.
         * column: "first_name".
         */
        String FIRST_NAME = (__ + ".firstName").intern();

        /**
         * Name of "middleName" property.
         * type: String.
         * column: "middle_name".
         */
        String MIDDLE_NAME = (__ + ".middleName").intern();

        /**
         * Name of "lastName" property.
         * type: String.
         * column: "last_name".
         */
        String LAST_NAME = (__ + ".lastName").intern();

        /**
         * Name of "birthDate" property.
         * type: Timestamp.
         * column: "birth_date".
         */
        String BIRTH_DATE = (__ + ".birthDate").intern();

        /**
         * Name of "status" property.
         * type: int.
         * column: "status".
         */
        String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property.
         * type: Timestamp.
         * column: "last_update_time".
         */
        String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property.
         * type: Timestamp.
         * column: "create_time".
         */
        String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Name of "contact" property.
         * type: com.landawn.abacus.entity.extendDirty.basic.AccountContact.
         * column: "AccountContact".
         */
        String CONTACT = (__ + ".contact").intern();

        /**
         * Name of "devices" property.
         * type: List<com.landawn.abacus.entity.extendDirty.basic.AccountDevice>.
         * column: "AccountDevice".
         */
        String DEVICES = (__ + ".devices").intern();

        /**
         * Immutable property name list
         */
        List<String> _PNL = Collections.unmodifiableList(
                Arrays.asList(ID, GUI, EMAIL_ADDRESS, FIRST_NAME, MIDDLE_NAME, LAST_NAME, BIRTH_DATE, STATUS, LAST_UPDATE_TIME, CREATE_TIME, CONTACT, DEVICES));

        /**
         * Immutable column name list
         */
        List<String> _CNL = Collections.unmodifiableList(Arrays.asList("account.id".intern(), "account.gui".intern(), "account.email_address".intern(),
                "account.first_name".intern(), "account.middle_name".intern(), "account.last_name".intern(), "account.birth_date".intern(),
                "account.status".intern(), "account.last_update_time".intern(), "account.create_time".intern()));
    }

    public interface Account1PNL {
        /**
         * Name of "Account1" entity.
         */
        String __ = "Account1";
    }

    public interface Account2PNL {
        /**
         * Name of "Account2" entity.
         */
        String __ = "Account2";
    }

    public interface AccountContactPNL {
        /**
         * Name of "AccountContact" entity.
         */
        String __ = "AccountContact".intern();

        /**
         * Name of "id" property.
         * type: long.
         * column: "id".
         */
        String ID = (__ + ".id").intern();

        /**
         * Name of "accountId" property.
         * type: long.
         * column: "account_id".
         */
        String ACCOUNT_ID = (__ + ".accountId").intern();

        /**
         * Name of "mobile" property.
         * type: String.
         * column: "mobile".
         */
        String MOBILE = (__ + ".mobile").intern();

        /**
         * Name of "telephone" property.
         * type: String.
         * column: "telephone".
         */
        String TELEPHONE = (__ + ".telephone").intern();

        /**
         * Name of "email" property.
         * type: String.
         * column: "email".
         */
        String EMAIL = (__ + ".email").intern();

        /**
         * Name of "address" property.
         * type: String.
         * column: "address".
         */
        String ADDRESS = (__ + ".address").intern();

        /**
         * Name of "address2" property.
         * type: String.
         * column: "address_2".
         */
        String ADDRESS_2 = (__ + ".address2").intern();

        /**
         * Name of "city" property.
         * type: String.
         * column: "city".
         */
        String CITY = (__ + ".city").intern();

        /**
         * Name of "state" property.
         * type: String.
         * column: "state".
         */
        String STATE = (__ + ".state").intern();

        /**
         * Name of "country" property.
         * type: String.
         * column: "country".
         */
        String COUNTRY = (__ + ".country").intern();

        /**
         * Name of "zipCode" property.
         * type: String.
         * column: "zip_code".
         */
        String ZIP_CODE = (__ + ".zipCode").intern();

        /**
         * Name of "category" property.
         * type: String.
         * column: "category".
         */
        String CATEGORY = (__ + ".category").intern();

        /**
         * Name of "description" property.
         * type: String.
         * column: "description".
         */
        String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property.
         * type: int.
         * column: "status".
         */
        String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property.
         * type: Timestamp.
         * column: "last_update_time".
         */
        String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property.
         * type: Timestamp.
         * column: "create_time".
         */
        String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, MOBILE, TELEPHONE, EMAIL, ADDRESS, ADDRESS_2, CITY, STATE, COUNTRY,
                ZIP_CODE, CATEGORY, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        List<String> _CNL = Collections.unmodifiableList(Arrays.asList("account_contact.id".intern(), "account_contact.account_id".intern(),
                "account_contact.mobile".intern(), "account_contact.telephone".intern(), "account_contact.email".intern(), "account_contact.address".intern(),
                "account_contact.address_2".intern(), "account_contact.city".intern(), "account_contact.state".intern(), "account_contact.country".intern(),
                "account_contact.zip_code".intern(), "account_contact.category".intern(), "account_contact.description".intern(),
                "account_contact.status".intern(), "account_contact.last_update_time".intern(), "account_contact.create_time".intern()));
    }

    public interface AccountDevicePNL {
        /**
         * Name of "AccountDevice" entity.
         */
        String __ = "AccountDevice".intern();

        /**
         * Name of "id" property.
         * type: long.
         * column: "id".
         */
        String ID = (__ + ".id").intern();

        /**
         * Name of "accountId" property.
         * type: long.
         * column: "account_id".
         */
        String ACCOUNT_ID = (__ + ".accountId").intern();

        /**
         * Name of "name" property.
         * type: String.
         * column: "name".
         */
        String NAME = (__ + ".name").intern();

        /**
         * Name of "UDID" property.
         * type: String.
         * column: "udid".
         */
        String UDID = (__ + ".UDID").intern();

        /**
         * Name of "platform" property.
         * type: String.
         * column: "platform".
         */
        String PLATFORM = (__ + ".platform").intern();

        /**
         * Name of "model" property.
         * type: String.
         * column: "model".
         */
        String MODEL = (__ + ".model").intern();

        /**
         * Name of "manufacturer" property.
         * type: String.
         * column: "manufacturer".
         */
        String MANUFACTURER = (__ + ".manufacturer").intern();

        /**
         * Name of "produceTime" property.
         * type: Timestamp.
         * column: "produce_time".
         */
        String PRODUCE_TIME = (__ + ".produceTime").intern();

        /**
         * Name of "category" property.
         * type: String.
         * column: "category".
         */
        String CATEGORY = (__ + ".category").intern();

        /**
         * Name of "description" property.
         * type: String.
         * column: "description".
         */
        String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property.
         * type: int.
         * column: "status".
         */
        String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property.
         * type: Timestamp.
         * column: "last_update_time".
         */
        String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property.
         * type: Timestamp.
         * column: "create_time".
         */
        String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, NAME, UDID, PLATFORM, MODEL, MANUFACTURER, PRODUCE_TIME, CATEGORY,
                DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        List<String> _CNL = Collections.unmodifiableList(Arrays.asList("account_device.id".intern(), "account_device.account_id".intern(),
                "account_device.name".intern(), "account_device.udid".intern(), "account_device.platform".intern(), "account_device.model".intern(),
                "account_device.manufacturer".intern(), "account_device.produce_time".intern(), "account_device.category".intern(),
                "account_device.description".intern(), "account_device.status".intern(), "account_device.last_update_time".intern(),
                "account_device.create_time".intern()));
    }

    public interface AclGroupPNL {
        /**
         * Name of "AclGroup" entity.
         */
        String __ = "AclGroup".intern();

        /**
         * Name of "id" property.
         * type: long.
         * column: "id".
         */
        String ID = (__ + ".id").intern();

        /**
         * Name of "gui" property.
         * type: String.
         * column: "gui".
         */
        String GUI = (__ + ".gui").intern();

        /**
         * Name of "name" property.
         * type: String.
         * column: "name".
         */
        String NAME = (__ + ".name").intern();

        /**
         * Name of "description" property.
         * type: String.
         * column: "description".
         */
        String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property.
         * type: int.
         * column: "status".
         */
        String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property.
         * type: Timestamp.
         * column: "last_update_time".
         */
        String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property.
         * type: Timestamp.
         * column: "create_time".
         */
        String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Name of "userList" property.
         * type: List<com.landawn.abacus.entity.extendDirty.basic.AclUser>.
         * column: "AclUser".
         */
        String USER_LIST = (__ + ".userList").intern();

        /**
         * Immutable property name list
         */
        List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, GUI, NAME, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME, USER_LIST));

        /**
         * Immutable column name list
         */
        List<String> _CNL = Collections.unmodifiableList(Arrays.asList("acl_group.id".intern(), "acl_group.gui".intern(), "acl_group.name".intern(),
                "acl_group.description".intern(), "acl_group.status".intern(), "acl_group.last_update_time".intern(), "acl_group.create_time".intern()));
    }

    public interface AclTargetPNL {
        /**
         * Name of "AclTarget" entity.
         */
        String __ = "AclTarget".intern();

        /**
         * Name of "id" property.
         * type: long.
         * column: "id".
         */
        String ID = (__ + ".id").intern();

        /**
         * Name of "gui" property.
         * type: String.
         * column: "gui".
         */
        String GUI = (__ + ".gui").intern();

        /**
         * Name of "name" property.
         * type: String.
         * column: "name".
         */
        String NAME = (__ + ".name").intern();

        /**
         * Name of "category" property.
         * type: String.
         * column: "category".
         */
        String CATEGORY = (__ + ".category").intern();

        /**
         * Name of "subCategory" property.
         * type: String.
         * column: "sub_category".
         */
        String SUB_CATEGORY = (__ + ".subCategory").intern();

        /**
         * Name of "type" property.
         * type: String.
         * column: "type".
         */
        String TYPE = (__ + ".type").intern();

        /**
         * Name of "subType" property.
         * type: String.
         * column: "sub_type".
         */
        String SUB_TYPE = (__ + ".subType").intern();

        /**
         * Name of "description" property.
         * type: String.
         * column: "description".
         */
        String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property.
         * type: int.
         * column: "status".
         */
        String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property.
         * type: Timestamp.
         * column: "last_update_time".
         */
        String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property.
         * type: Timestamp.
         * column: "create_time".
         */
        String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        List<String> _PNL = Collections
                .unmodifiableList(Arrays.asList(ID, GUI, NAME, CATEGORY, SUB_CATEGORY, TYPE, SUB_TYPE, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        List<String> _CNL = Collections.unmodifiableList(Arrays.asList("acl_target.id".intern(), "acl_target.gui".intern(), "acl_target.name".intern(),
                "acl_target.category".intern(), "acl_target.sub_category".intern(), "acl_target.type".intern(), "acl_target.sub_type".intern(),
                "acl_target.description".intern(), "acl_target.status".intern(), "acl_target.last_update_time".intern(), "acl_target.create_time".intern()));
    }

    public interface AclUgTargetRelationshipPNL {
        /**
         * Name of "AclUgTargetRelationship" entity.
         */
        String __ = "AclUgTargetRelationship".intern();

        /**
         * Name of "id" property.
         * type: long.
         * column: "id".
         */
        String ID = (__ + ".id").intern();

        /**
         * Name of "ugGui" property.
         * type: String.
         * column: "ug_gui".
         */
        String UG_GUI = (__ + ".ugGui").intern();

        /**
         * Name of "targetGui" property.
         * type: String.
         * column: "target_gui".
         */
        String TARGET_GUI = (__ + ".targetGui").intern();

        /**
         * Name of "privilege" property.
         * type: long.
         * column: "privilege".
         */
        String PRIVILEGE = (__ + ".privilege").intern();

        /**
         * Name of "description" property.
         * type: String.
         * column: "description".
         */
        String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property.
         * type: int.
         * column: "status".
         */
        String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property.
         * type: Timestamp.
         * column: "last_update_time".
         */
        String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property.
         * type: Timestamp.
         * column: "create_time".
         */
        String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, UG_GUI, TARGET_GUI, PRIVILEGE, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        List<String> _CNL = Collections.unmodifiableList(Arrays.asList("acl_ug_target_relationship.id".intern(), "acl_ug_target_relationship.ug_gui".intern(),
                "acl_ug_target_relationship.target_gui".intern(), "acl_ug_target_relationship.privilege".intern(),
                "acl_ug_target_relationship.description".intern(), "acl_ug_target_relationship.status".intern(),
                "acl_ug_target_relationship.last_update_time".intern(), "acl_ug_target_relationship.create_time".intern()));
    }

    public interface AclUserPNL {
        /**
         * Name of "AclUser" entity.
         */
        String __ = "AclUser".intern();

        /**
         * Name of "id" property.
         * type: long.
         * column: "id".
         */
        String ID = (__ + ".id").intern();

        /**
         * Name of "gui" property.
         * type: String.
         * column: "gui".
         */
        String GUI = (__ + ".gui").intern();

        /**
         * Name of "name" property.
         * type: String.
         * column: "name".
         */
        String NAME = (__ + ".name").intern();

        /**
         * Name of "description" property.
         * type: String.
         * column: "description".
         */
        String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property.
         * type: int.
         * column: "status".
         */
        String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property.
         * type: Timestamp.
         * column: "last_update_time".
         */
        String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property.
         * type: Timestamp.
         * column: "create_time".
         */
        String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Name of "groupList" property.
         * type: List<com.landawn.abacus.entity.extendDirty.basic.AclGroup>.
         * column: "AclGroup".
         */
        String GROUP_LIST = (__ + ".groupList").intern();

        /**
         * Immutable property name list
         */
        List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, GUI, NAME, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME, GROUP_LIST));

        /**
         * Immutable column name list
         */
        List<String> _CNL = Collections.unmodifiableList(Arrays.asList("acl_user.id".intern(), "acl_user.gui".intern(), "acl_user.name".intern(),
                "acl_user.description".intern(), "acl_user.status".intern(), "acl_user.last_update_time".intern(), "acl_user.create_time".intern()));
    }

    public interface AclUserGroupRelationshipPNL {
        /**
         * Name of "AclUserGroupRelationship" entity.
         */
        String __ = "AclUserGroupRelationship".intern();

        /**
         * Name of "id" property.
         * type: long.
         * column: "id".
         */
        String ID = (__ + ".id").intern();

        /**
         * Name of "userGUI" property.
         * type: String.
         * column: "user_gui".
         */
        String USER_GUI = (__ + ".userGUI").intern();

        /**
         * Name of "groupGUI" property.
         * type: String.
         * column: "group_gui".
         */
        String GROUP_GUI = (__ + ".groupGUI").intern();

        /**
         * Name of "description" property.
         * type: String.
         * column: "description".
         */
        String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property.
         * type: int.
         * column: "status".
         */
        String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property.
         * type: Timestamp.
         * column: "last_update_time".
         */
        String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property.
         * type: Timestamp.
         * column: "create_time".
         */
        String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, USER_GUI, GROUP_GUI, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        List<String> _CNL = Collections.unmodifiableList(Arrays.asList("acl_user_group_relationship.id".intern(),
                "acl_user_group_relationship.user_gui".intern(), "acl_user_group_relationship.group_gui".intern(),
                "acl_user_group_relationship.description".intern(), "acl_user_group_relationship.status".intern(),
                "acl_user_group_relationship.last_update_time".intern(), "acl_user_group_relationship.create_time".intern()));
    }

    public interface DataTypePNL {
        /**
         * Name of "DataType" entity.
         */
        String __ = "DataType".intern();

        /**
         * Name of "byteType" property.
         * type: byte.
         * column: "bytetype".
         */
        String BYTE_TYPE = (__ + ".byteType").intern();

        /**
         * Name of "charType" property.
         * type: char.
         * column: "chartype".
         */
        String CHAR_TYPE = (__ + ".charType").intern();

        /**
         * Name of "booleanType" property.
         * type: boolean.
         * column: "booleantype".
         */
        String BOOLEAN_TYPE = (__ + ".booleanType").intern();

        /**
         * Name of "shortType" property.
         * type: short.
         * column: "shorttype".
         */
        String SHORT_TYPE = (__ + ".shortType").intern();

        /**
         * Name of "intType" property.
         * type: int.
         * column: "inttype".
         */
        String INT_TYPE = (__ + ".intType").intern();

        /**
         * Name of "longType" property.
         * type: long.
         * column: "longtype".
         */
        String LONG_TYPE = (__ + ".longType").intern();

        /**
         * Name of "floatType" property.
         * type: float.
         * column: "floattype".
         */
        String FLOAT_TYPE = (__ + ".floatType").intern();

        /**
         * Name of "doubleType" property.
         * type: double.
         * column: "doubletype".
         */
        String DOUBLE_TYPE = (__ + ".doubleType").intern();

        /**
         * Name of "bigIntegerType" property.
         * type: BigInteger.
         * column: "bigIntegerType".
         */
        String BIG_INTEGER_TYPE = (__ + ".bigIntegerType").intern();

        /**
         * Name of "bigDecimalType" property.
         * type: BigDecimal.
         * column: "bigdecimaltype".
         */
        String BIG_DECIMAL_TYPE = (__ + ".bigDecimalType").intern();

        /**
         * Name of "stringType" property.
         * type: String.
         * column: "stringtype".
         */
        String STRING_TYPE = (__ + ".stringType").intern();

        /**
         * Name of "byteArrayType" property.
         * type: byte[].
         * column: "bytearraytype".
         */
        String BYTE_ARRAY_TYPE = (__ + ".byteArrayType").intern();

        /**
         * Name of "characterStreamType" property.
         * type: CharacterStream.
         * column: "characterstreamtype".
         */
        String CHARACTER_STREAM_TYPE = (__ + ".characterStreamType").intern();

        /**
         * Name of "binaryStreamType" property.
         * type: BinaryStream.
         * column: "binarystreamtype".
         */
        String BINARY_STREAM_TYPE = (__ + ".binaryStreamType").intern();

        /**
         * Name of "clobType" property.
         * type: Clob.
         * column: "clobtype".
         */
        String CLOB_TYPE = (__ + ".clobType").intern();

        /**
         * Name of "blobType" property.
         * type: Blob.
         * column: "blobtype".
         */
        String BLOB_TYPE = (__ + ".blobType").intern();

        /**
         * Name of "dateType" property.
         * type: Date.
         * column: "datetype".
         */
        String DATE_TYPE = (__ + ".dateType").intern();

        /**
         * Name of "timeType" property.
         * type: Time.
         * column: "timetype".
         */
        String TIME_TYPE = (__ + ".timeType").intern();

        /**
         * Name of "timestampType" property.
         * type: Timestamp.
         * column: "timestamptype".
         */
        String TIMESTAMP_TYPE = (__ + ".timestampType").intern();

        /**
         * Name of "longDateType" property.
         * type: long.
         * column: "longDateType".
         */
        String LONG_DATE_TYPE = (__ + ".longDateType").intern();

        /**
         * Name of "longTimeType" property.
         * type: long.
         * column: "longTimeType".
         */
        String LONG_TIME_TYPE = (__ + ".longTimeType").intern();

        /**
         * Name of "longTimestampType" property.
         * type: long.
         * column: "longTimestampType".
         */
        String LONG_TIMESTAMP_TYPE = (__ + ".longTimestampType").intern();

        /**
         * Name of "enumType" property.
         * type: com.landawn.abacus.types.WeekDay.
         * column: "enumType".
         */
        String ENUM_TYPE = (__ + ".enumType").intern();

        /**
         * Name of "stringArrayListType" property.
         * type: ArrayList<String>.
         * column: "stringarraylisttype".
         */
        String STRING_ARRAY_LIST_TYPE = (__ + ".stringArrayListType").intern();

        /**
         * Name of "booleanLinkedListType" property.
         * type: LinkedList<Boolean>.
         * column: "booleanlinkedlisttype".
         */
        String BOOLEAN_LINKED_LIST_TYPE = (__ + ".booleanLinkedListType").intern();

        /**
         * Name of "doubleListType" property.
         * type: List<Double>.
         * column: "doublearraylisttype".
         */
        String DOUBLE_LIST_TYPE = (__ + ".doubleListType").intern();

        /**
         * Name of "dateArrayListType" property.
         * type: ArrayList<Date>.
         * column: "datearraylisttype".
         */
        String DATE_ARRAY_LIST_TYPE = (__ + ".dateArrayListType").intern();

        /**
         * Name of "timestampArrayListType" property.
         * type: ArrayList<Timestamp>.
         * column: "timestamparraylisttype".
         */
        String TIMESTAMP_ARRAY_LIST_TYPE = (__ + ".timestampArrayListType").intern();

        /**
         * Name of "bigDecimalArrayListType" property.
         * type: ArrayList<BigDecimal>.
         * column: "bigdecimalarraylisttype".
         */
        String BIG_DECIMAL_ARRAY_LIST_TYPE = (__ + ".bigDecimalArrayListType").intern();

        /**
         * Name of "stringHashSetType" property.
         * type: HashSet<String>.
         * column: "stringhashsettype".
         */
        String STRING_HASH_SET_TYPE = (__ + ".stringHashSetType").intern();

        /**
         * Name of "booleanLinkedHashSetType" property.
         * type: LinkedHashSet<Boolean>.
         * column: "booleanlinkedhashsettype".
         */
        String BOOLEAN_LINKED_HASH_SET_TYPE = (__ + ".booleanLinkedHashSetType").intern();

        /**
         * Name of "dateHashSetType" property.
         * type: HashSet<Date>.
         * column: "datehashsettype".
         */
        String DATE_HASH_SET_TYPE = (__ + ".dateHashSetType").intern();

        /**
         * Name of "timestampHashSetType" property.
         * type: HashSet<Timestamp>.
         * column: "timestamphashsettype".
         */
        String TIMESTAMP_HASH_SET_TYPE = (__ + ".timestampHashSetType").intern();

        /**
         * Name of "bigDecimalHashSetType" property.
         * type: HashSet<BigDecimal>.
         * column: "bigdecimalhashsettype".
         */
        String BIG_DECIMAL_HASH_SET_TYPE = (__ + ".bigDecimalHashSetType").intern();

        /**
         * Name of "stringHashMapType" property.
         * type: HashMap<String, String>.
         * column: "stringhashmaptype".
         */
        String STRING_HASH_MAP_TYPE = (__ + ".stringHashMapType").intern();

        /**
         * Name of "booleanLinkedHashMapType" property.
         * type: LinkedHashMap<String, Boolean>.
         * column: "booleanlinkedhashmaptype".
         */
        String BOOLEAN_LINKED_HASH_MAP_TYPE = (__ + ".booleanLinkedHashMapType").intern();

        /**
         * Name of "floatHashMapType" property.
         * type: HashMap<String, Float>.
         * column: "floathashmaptype".
         */
        String FLOAT_HASH_MAP_TYPE = (__ + ".floatHashMapType").intern();

        /**
         * Name of "dateHashMapType" property.
         * type: HashMap<String, Date>.
         * column: "datehashmaptype".
         */
        String DATE_HASH_MAP_TYPE = (__ + ".dateHashMapType").intern();

        /**
         * Name of "timestampHashMapType" property.
         * type: HashMap<Timestamp, Float>.
         * column: "timestamphashmaptype".
         */
        String TIMESTAMP_HASH_MAP_TYPE = (__ + ".timestampHashMapType").intern();

        /**
         * Name of "bigDecimalHashMapType" property.
         * type: HashMap<BigDecimal, String>.
         * column: "bigdecimalhashmaptype".
         */
        String BIG_DECIMAL_HASH_MAP_TYPE = (__ + ".bigDecimalHashMapType").intern();

        /**
         * Name of "stringVectorType" property.
         * type: Vector<String>.
         * column: "stringvectortype".
         */
        String STRING_VECTOR_TYPE = (__ + ".stringVectorType").intern();

        /**
         * Name of "stringConcurrentHashMapType" property.
         * type: ConcurrentHashMap<BigDecimal, String>.
         * column: "stringconcurrenthashmaptype".
         */
        String STRING_CONCURRENT_HASH_MAP_TYPE = (__ + ".stringConcurrentHashMapType").intern();

        /**
         * Name of "jsonType" property.
         * type: JSON<com.landawn.abacus.entity.extendDirty.lvc.Account>.
         * column: "jsonType".
         */
        String JSON_TYPE = (__ + ".jsonType").intern();

        /**
         * Name of "xmlType" property.
         * type: XML<com.landawn.abacus.entity.extendDirty.lvc.Account>.
         * column: "xmlType".
         */
        String XML_TYPE = (__ + ".xmlType").intern();

        /**
         * Immutable property name list
         */
        List<String> _PNL = Collections.unmodifiableList(Arrays.asList(BYTE_TYPE, CHAR_TYPE, BOOLEAN_TYPE, SHORT_TYPE, INT_TYPE, LONG_TYPE, FLOAT_TYPE,
                DOUBLE_TYPE, BIG_INTEGER_TYPE, BIG_DECIMAL_TYPE, STRING_TYPE, BYTE_ARRAY_TYPE, CHARACTER_STREAM_TYPE, BINARY_STREAM_TYPE, CLOB_TYPE, BLOB_TYPE,
                DATE_TYPE, TIME_TYPE, TIMESTAMP_TYPE, LONG_DATE_TYPE, LONG_TIME_TYPE, LONG_TIMESTAMP_TYPE, ENUM_TYPE, STRING_ARRAY_LIST_TYPE,
                BOOLEAN_LINKED_LIST_TYPE, DOUBLE_LIST_TYPE, DATE_ARRAY_LIST_TYPE, TIMESTAMP_ARRAY_LIST_TYPE, BIG_DECIMAL_ARRAY_LIST_TYPE, STRING_HASH_SET_TYPE,
                BOOLEAN_LINKED_HASH_SET_TYPE, DATE_HASH_SET_TYPE, TIMESTAMP_HASH_SET_TYPE, BIG_DECIMAL_HASH_SET_TYPE, STRING_HASH_MAP_TYPE,
                BOOLEAN_LINKED_HASH_MAP_TYPE, FLOAT_HASH_MAP_TYPE, DATE_HASH_MAP_TYPE, TIMESTAMP_HASH_MAP_TYPE, BIG_DECIMAL_HASH_MAP_TYPE, STRING_VECTOR_TYPE,
                STRING_CONCURRENT_HASH_MAP_TYPE, JSON_TYPE, XML_TYPE));

        /**
         * Immutable column name list
         */
        List<String> _CNL = Collections.unmodifiableList(Arrays.asList("data_type.bytetype".intern(), "data_type.chartype".intern(),
                "data_type.booleantype".intern(), "data_type.shorttype".intern(), "data_type.inttype".intern(), "data_type.longtype".intern(),
                "data_type.floattype".intern(), "data_type.doubletype".intern(), "data_type.bigIntegerType".intern(), "data_type.bigdecimaltype".intern(),
                "data_type.stringtype".intern(), "data_type.bytearraytype".intern(), "data_type.characterstreamtype".intern(),
                "data_type.binarystreamtype".intern(), "data_type.clobtype".intern(), "data_type.blobtype".intern(), "data_type.datetype".intern(),
                "data_type.timetype".intern(), "data_type.timestamptype".intern(), "data_type.longDateType".intern(), "data_type.longTimeType".intern(),
                "data_type.longTimestampType".intern(), "data_type.enumType".intern(), "data_type.stringarraylisttype".intern(),
                "data_type.booleanlinkedlisttype".intern(), "data_type.doublearraylisttype".intern(), "data_type.datearraylisttype".intern(),
                "data_type.timestamparraylisttype".intern(), "data_type.bigdecimalarraylisttype".intern(), "data_type.stringhashsettype".intern(),
                "data_type.booleanlinkedhashsettype".intern(), "data_type.datehashsettype".intern(), "data_type.timestamphashsettype".intern(),
                "data_type.bigdecimalhashsettype".intern(), "data_type.stringhashmaptype".intern(), "data_type.booleanlinkedhashmaptype".intern(),
                "data_type.floathashmaptype".intern(), "data_type.datehashmaptype".intern(), "data_type.timestamphashmaptype".intern(),
                "data_type.bigdecimalhashmaptype".intern(), "data_type.stringvectortype".intern(), "data_type.stringconcurrenthashmaptype".intern(),
                "data_type.jsonType".intern(), "data_type.xmlType".intern()));
    }

    public interface LoginPNL {
        /**
         * Name of "Login" entity.
         */
        String __ = "Login".intern();

        /**
         * Name of "id" property.
         * type: long.
         * column: "id".
         */
        String ID = (__ + ".id").intern();

        /**
         * Name of "accountId" property.
         * type: long.
         * column: "account_id".
         */
        String ACCOUNT_ID = (__ + ".accountId").intern();

        /**
         * Name of "loginId" property.
         * type: String.
         * column: "login_id".
         */
        String LOGIN_ID = (__ + ".loginId").intern();

        /**
         * Name of "loginPassword" property.
         * type: String.
         * column: "login_password".
         */
        String LOGIN_PASSWORD = (__ + ".loginPassword").intern();

        /**
         * Name of "status" property.
         * type: int.
         * column: "status".
         */
        String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property.
         * type: Timestamp.
         * column: "last_update_time".
         */
        String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property.
         * type: Timestamp.
         * column: "create_time".
         */
        String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, LOGIN_ID, LOGIN_PASSWORD, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        List<String> _CNL = Collections.unmodifiableList(Arrays.asList("login.id".intern(), "login.account_id".intern(), "login.login_id".intern(),
                "login.login_password".intern(), "login.status".intern(), "login.last_update_time".intern(), "login.create_time".intern()));
    }

    String ACCOUNT_ID = "accountId".intern();

    String ADDRESS = "address".intern();

    String ADDRESS_2 = "address2".intern();

    String BIG_DECIMAL_ARRAY_LIST_TYPE = "bigDecimalArrayListType".intern();

    String BIG_DECIMAL_HASH_MAP_TYPE = "bigDecimalHashMapType".intern();

    String BIG_DECIMAL_HASH_SET_TYPE = "bigDecimalHashSetType".intern();

    String BIG_DECIMAL_TYPE = "bigDecimalType".intern();

    String BIG_INTEGER_TYPE = "bigIntegerType".intern();

    String BINARY_STREAM_TYPE = "binaryStreamType".intern();

    String BIRTH_DATE = "birthDate".intern();

    String BLOB_TYPE = "blobType".intern();

    String BOOLEAN_LINKED_HASH_MAP_TYPE = "booleanLinkedHashMapType".intern();

    String BOOLEAN_LINKED_HASH_SET_TYPE = "booleanLinkedHashSetType".intern();

    String BOOLEAN_LINKED_LIST_TYPE = "booleanLinkedListType".intern();

    String BOOLEAN_TYPE = "booleanType".intern();

    String BYTE_ARRAY_TYPE = "byteArrayType".intern();

    String BYTE_TYPE = "byteType".intern();

    String CATEGORY = "category".intern();

    String CHARACTER_STREAM_TYPE = "characterStreamType".intern();

    String CHAR_TYPE = "charType".intern();

    String CITY = "city".intern();

    String CLOB_TYPE = "clobType".intern();

    String CONTACT = "contact".intern();

    String COUNTRY = "country".intern();

    String CREATE_TIME = "createTime".intern();

    String DATE_ARRAY_LIST_TYPE = "dateArrayListType".intern();

    String DATE_HASH_MAP_TYPE = "dateHashMapType".intern();

    String DATE_HASH_SET_TYPE = "dateHashSetType".intern();

    String DATE_TYPE = "dateType".intern();

    String DESCRIPTION = "description".intern();

    String DEVICES = "devices".intern();

    String DOUBLE_LIST_TYPE = "doubleListType".intern();

    String DOUBLE_TYPE = "doubleType".intern();

    String EMAIL = "email".intern();

    String EMAIL_ADDRESS = "emailAddress".intern();

    String ENUM_TYPE = "enumType".intern();

    String FIRST_NAME = "firstName".intern();

    String FLOAT_HASH_MAP_TYPE = "floatHashMapType".intern();

    String FLOAT_TYPE = "floatType".intern();

    String GROUP_GUI = "groupGUI".intern();

    String GROUP_LIST = "groupList".intern();

    String GUI = "gui".intern();

    String ID = "id".intern();

    String INT_TYPE = "intType".intern();

    String JSON_TYPE = "jsonType".intern();

    String LAST_NAME = "lastName".intern();

    String LAST_UPDATE_TIME = "lastUpdateTime".intern();

    String LOGIN_ID = "loginId".intern();

    String LOGIN_PASSWORD = "loginPassword".intern();

    String LONG_DATE_TYPE = "longDateType".intern();

    String LONG_TIMESTAMP_TYPE = "longTimestampType".intern();

    String LONG_TIME_TYPE = "longTimeType".intern();

    String LONG_TYPE = "longType".intern();

    String MANUFACTURER = "manufacturer".intern();

    String MIDDLE_NAME = "middleName".intern();

    String MOBILE = "mobile".intern();

    String MODEL = "model".intern();

    String NAME = "name".intern();

    String PLATFORM = "platform".intern();

    String PRIVILEGE = "privilege".intern();

    String PRODUCE_TIME = "produceTime".intern();

    String SHORT_TYPE = "shortType".intern();

    String STATE = "state".intern();

    String STATUS = "status".intern();

    String STRING_ARRAY_LIST_TYPE = "stringArrayListType".intern();

    String STRING_CONCURRENT_HASH_MAP_TYPE = "stringConcurrentHashMapType".intern();

    String STRING_HASH_MAP_TYPE = "stringHashMapType".intern();

    String STRING_HASH_SET_TYPE = "stringHashSetType".intern();

    String STRING_TYPE = "stringType".intern();

    String STRING_VECTOR_TYPE = "stringVectorType".intern();

    String SUB_CATEGORY = "subCategory".intern();

    String SUB_TYPE = "subType".intern();

    String TARGET_GUI = "targetGui".intern();

    String TELEPHONE = "telephone".intern();

    String TIMESTAMP_ARRAY_LIST_TYPE = "timestampArrayListType".intern();

    String TIMESTAMP_HASH_MAP_TYPE = "timestampHashMapType".intern();

    String TIMESTAMP_HASH_SET_TYPE = "timestampHashSetType".intern();

    String TIMESTAMP_TYPE = "timestampType".intern();

    String TIME_TYPE = "timeType".intern();

    String TYPE = "type".intern();

    String UDID = "UDID".intern();

    String UG_GUI = "ugGui".intern();

    String USER_GUI = "userGUI".intern();

    String USER_LIST = "userList".intern();

    String XML_TYPE = "xmlType".intern();

    String ZIP_CODE = "zipCode".intern();
}
