/*
 * Copyright (c) 2015, Haiyang Li. All rights reserved.
 */

package com.landawn.abacus.da;

import java.sql.Timestamp;
import java.util.List;

import javax.xml.bind.annotation.XmlTransient;

import com.landawn.abacus.da.entity.AccountContact;
import com.landawn.abacus.da.entity.AccountDevice;
import com.landawn.abacus.da.entity.ExtendDirtyBasicPNL;
import com.landawn.abacus.util.N;

/**
 * Generated by Abacus. DO NOT edit it!
 *
 *
 */
public class Account implements ExtendDirtyBasicPNL.AccountPNL {
    private String id;
    private String gui;
    private String emailAddress;
    private String firstName;
    private String middleName;
    private String lastName;
    private Timestamp birthDate;
    private int status;
    private Timestamp lastUpdateTime;
    private Timestamp createTime;
    private AccountContact contact;
    private List<AccountDevice> devices;

    /**
     */
    public Account() {
    }

    /**
     * 
     *
     * @param id 
     */
    public Account(String id) {
        this();

        setId(id);
    }

    /**
     * 
     *
     * @param gui 
     * @param emailAddress 
     * @param firstName 
     * @param middleName 
     * @param lastName 
     * @param birthDate 
     * @param status 
     * @param lastUpdateTime 
     * @param createTime 
     * @param contact 
     * @param devices 
     */
    public Account(String gui, String emailAddress, String firstName, String middleName, String lastName, Timestamp birthDate, int status,
            Timestamp lastUpdateTime, Timestamp createTime, AccountContact contact, List<AccountDevice> devices) {
        this();

        setGUI(gui);
        setEmailAddress(emailAddress);
        setFirstName(firstName);
        setMiddleName(middleName);
        setLastName(lastName);
        setBirthDate(birthDate);
        setStatus(status);
        setLastUpdateTime(lastUpdateTime);
        setCreateTime(createTime);
        setContact(contact);
        setDevices(devices);
    }

    /**
     * 
     *
     * @param id 
     * @param gui 
     * @param emailAddress 
     * @param firstName 
     * @param middleName 
     * @param lastName 
     * @param birthDate 
     * @param status 
     * @param lastUpdateTime 
     * @param createTime 
     * @param contact 
     * @param devices 
     */
    public Account(String id, String gui, String emailAddress, String firstName, String middleName, String lastName, Timestamp birthDate, int status,
            Timestamp lastUpdateTime, Timestamp createTime, AccountContact contact, List<AccountDevice> devices) {
        this();

        setId(id);
        setGUI(gui);
        setEmailAddress(emailAddress);
        setFirstName(firstName);
        setMiddleName(middleName);
        setLastName(lastName);
        setBirthDate(birthDate);
        setStatus(status);
        setLastUpdateTime(lastUpdateTime);
        setCreateTime(createTime);
        setContact(contact);
        setDevices(devices);
    }

    /**
     * 
     *
     * @return 
     */
    @XmlTransient

    public String getId() {
        return id;
    }

    /**
     * 
     *
     * @param id 
     * @return 
     */
    public Account setId(String id) {
        this.id = id;

        return this;
    }

    /**
     * 
     *
     * @return 
     */
    public String getGUI() {
        return gui;
    }

    /**
     * 
     *
     * @param gui 
     * @return 
     */
    public Account setGUI(String gui) {
        this.gui = gui;

        return this;
    }

    /**
     * 
     *
     * @return 
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * 
     *
     * @param emailAddress 
     * @return 
     */
    public Account setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;

        return this;
    }

    /**
     * 
     *
     * @return 
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * 
     *
     * @param firstName 
     * @return 
     */
    public Account setFirstName(String firstName) {
        this.firstName = firstName;

        return this;
    }

    /**
     * 
     *
     * @return 
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * 
     *
     * @param middleName 
     * @return 
     */
    public Account setMiddleName(String middleName) {
        this.middleName = middleName;

        return this;
    }

    /**
     * 
     *
     * @return 
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * 
     *
     * @param lastName 
     * @return 
     */
    public Account setLastName(String lastName) {
        this.lastName = lastName;

        return this;
    }

    /**
     * 
     *
     * @return 
     */
    public Timestamp getBirthDate() {
        return birthDate;
    }

    /**
     * 
     *
     * @param birthDate 
     * @return 
     */
    public Account setBirthDate(Timestamp birthDate) {
        this.birthDate = birthDate;

        return this;
    }

    /**
     * 
     *
     * @return 
     */
    public int getStatus() {
        return status;
    }

    /**
     * 
     *
     * @param status 
     * @return 
     */
    public Account setStatus(int status) {
        this.status = status;

        return this;
    }

    /**
     * 
     *
     * @return 
     */
    public Timestamp getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * 
     *
     * @param lastUpdateTime 
     * @return 
     */
    public Account setLastUpdateTime(Timestamp lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;

        return this;
    }

    /**
     * 
     *
     * @return 
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * 
     *
     * @param createTime 
     * @return 
     */
    public Account setCreateTime(Timestamp createTime) {
        this.createTime = createTime;

        return this;
    }

    /**
     * 
     *
     * @return 
     */
    public AccountContact getContact() {
        return contact;
    }

    /**
     * 
     *
     * @param contact 
     * @return 
     */
    public Account setContact(AccountContact contact) {
        this.contact = contact;

        return this;
    }

    /**
     * 
     *
     * @return 
     */
    public List<AccountDevice> getDevices() {
        return devices;
    }

    /**
     * 
     *
     * @param devices 
     * @return 
     */
    public Account setDevices(List<AccountDevice> devices) {
        this.devices = devices;

        return this;
    }

    /**
     * 
     *
     * @return 
     */
    public Account copy() {
        Account copy = new Account();

        copy.id = this.id;
        copy.gui = this.gui;
        copy.emailAddress = this.emailAddress;
        copy.firstName = this.firstName;
        copy.middleName = this.middleName;
        copy.lastName = this.lastName;
        copy.birthDate = this.birthDate;
        copy.status = this.status;
        copy.lastUpdateTime = this.lastUpdateTime;
        copy.createTime = this.createTime;
        copy.contact = this.contact;
        copy.devices = this.devices;

        return copy;
    }

    /**
     * 
     *
     * @return 
     */
    @Override
    public int hashCode() {
        int h = 17;
        h = 31 * h + N.hashCode(id);
        h = 31 * h + N.hashCode(gui);
        h = 31 * h + N.hashCode(emailAddress);
        h = 31 * h + N.hashCode(firstName);
        h = 31 * h + N.hashCode(middleName);
        h = 31 * h + N.hashCode(lastName);
        h = 31 * h + N.hashCode(birthDate);
        h = 31 * h + N.hashCode(status);
        h = 31 * h + N.hashCode(lastUpdateTime);
        h = 31 * h + N.hashCode(createTime);
        h = 31 * h + N.hashCode(contact);
        return 31 * h + N.hashCode(devices);
    }

    /**
     * 
     *
     * @param obj 
     * @return 
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj instanceof Account other) {
            if (N.equals(id, other.id) && N.equals(gui, other.gui) && N.equals(emailAddress, other.emailAddress) && N.equals(firstName, other.firstName)
                    && N.equals(middleName, other.middleName) && N.equals(lastName, other.lastName) && N.equals(birthDate, other.birthDate)
                    && N.equals(status, other.status) && N.equals(lastUpdateTime, other.lastUpdateTime) && N.equals(createTime, other.createTime)
                    && N.equals(contact, other.contact) && N.equals(devices, other.devices)) {

                return true;
            }
        }

        return false;
    }

    /**
     * 
     *
     * @return 
     */
    @Override
    public String toString() {
        return "{" + "id=" + N.toString(id) + ", " + "gui=" + N.toString(gui) + ", " + "emailAddress=" + N.toString(emailAddress) + ", " + "firstName="
                + N.toString(firstName) + ", " + "middleName=" + N.toString(middleName) + ", " + "lastName=" + N.toString(lastName) + ", " + "birthDate="
                + N.toString(birthDate) + ", " + "status=" + N.toString(status) + ", " + "lastUpdateTime=" + N.toString(lastUpdateTime) + ", " + "createTime="
                + N.toString(createTime) + ", " + "contact=" + N.toString(contact) + ", " + "devices=" + N.toString(devices) + "}";
    }
}
